from enum import Enum


class Action(Enum):
    BUY_PROPERTY = "BUY_PROPERTY"
    DO_NOT_BUY_PROPERTY = "DO_NOT_BUY_PROPERTY"
    ROLL_AGAIN = "ROLL_AGAIN"
    CHANCE = "CHANCE"
    END_TURN = "END_TURN"
    BID = "BID"
    PASS = "PASS"
    EXIT_AUCTION = "EXIT_AUCTION"
    MANAGE = "MANAGE"
    SELECT_PROPERTY = "SELECT_PROPERTY"
    BUY = "BUY"
    MORGAGE = "MORGAGE"
    TRADE = "TRADE"
    SELECT_OTHER_PLAYER = "SELECT_OTHER_PLAYER"
    SELECT_PROPERTY_AND_AMOUNT = "SELECT_PROPERTY_AND_AMOUNT"
    PROPOSE_TRADE = "PROPOSE_TRADE"
    CANCEL_TRADE = "CANCEL_TRADE"

class ExtraAction(Enum):
    INITIALIZE = "INITIALIZE"
    ROLL_DICE = "ROLL_DICE"

#def str_to_action(action_str: str) -> Action:
#    return Action(action_str)
